create table topics(
    id        bigint generated by default as identity primary key,
    name      varchar(100) not null,
    parent_id bigint references topics (id),
    constraint uq_topic_name_parent unique (name, parent_id)
);

create table questions(
    id            bigint generated by default as identity primary key,
    topic_id      bigint not null references topics (id),
    question_text text   not null,
    answer_text   text   not null,
    created_at    timestamptz default now()
);

CREATE TABLE languages_items(
    id          bigint generated by default as identity primary key,
    topic_id    bigint references topics (id),
    language    varchar(10) not null, -- EN, DE
    type        varchar(30) not null, -- WORD | IRREGULAR_VERB | PHRASE
    word        text        not null,
    translation text        not null,
    example     text,
    created_at  timestamptz default now(),
    constraint uq_language_item unique (language, type, word)
);

create table srs_reviews(
    id               bigint generated by default as identity primary key,
    item_type        varchar(30) not null, -- QUESTION | LANGUAGE_ITEM
    item_id          bigint      not null, -- id из questions или languages_items
    stage            int         not null default 0,
    next_review_at   timestamptz not null,
    last_reviewed_at timestamptz,
    correct_in_row   int         not null default 0,
    archived         boolean     not null default false,
    created_at       timestamptz          default now(),
    constraint uq_review unique (item_type, item_id)
);
------------------------------------------------------
-- Пример заполнения

-- topic
INSERT INTO topics (name, parent_id) VALUES ('Spring', NULL);
INSERT INTO topics (name, parent_id) VALUES ('Spring Core', 1);
INSERT INTO topics (name, parent_id) VALUES ('Spring MVC', 1);

INSERT INTO topics (name, parent_id) VALUES ('English', NULL);
INSERT INTO topics (name, parent_id) VALUES ('Java Core', 4);
INSERT INTO topics (name, parent_id) VALUES ('Concurrency', 4);

update topics set parent_id = 8 where id = 9;

-- язык
INSERT INTO languages_items(language, type, word, translation, example)
VALUES ('EN', 'WORD', 'achieve', 'достигать', 'I want to achieve my goals.');

-- вопрос
INSERT INTO questions(topic_id, question_text, answer_text)
VALUES (1, 'Что такое HashMap?', 'HashMap хранит пары ключ-значение.');

-- review для слова
INSERT INTO srs_reviews(item_type, item_id, next_review_at)
VALUES ('LANGUAGE_ITEM', 1, now() + interval '8 hours');

-- review для вопроса
INSERT INTO srs_reviews(item_type, item_id, next_review_at)
VALUES ('QUESTION', 1, now() + interval '8 hours');
