create table topics(
    id        bigint generated by default as identity primary key,
    name      varchar(100) not null,
    parent_id bigint references topics (id),
    constraint uq_topic_name_parent unique (name, parent_id)
);

create table questions(
    id            bigint generated by default as identity primary key,
    topic_id      bigint not null references topics (id),
    question_text text   not null,
    answer_text   text   not null,
    created_at    timestamptz default now()
);

create table question_review(
    id               bigint generated by default as identity primary key,
    question_id      bigint      not null references questions (id) on delete cascade,
    stage            int         not null default 0,
    next_review_at   timestamptz not null,
    last_reviewed_at timestamptz,
    correct_in_row   int         not null default 0,
    archived         boolean     not null default false
);