-- Таблица для медиафайлов
CREATE TABLE media_files (
    id            bigint generated by default as identity primary key,
    filename      varchar(255) not null,       -- uuid.ext — имя файла на диске
    original_name varchar(255) not null,       -- оригинальное имя от пользователя
    content_type  varchar(100) not null,       -- image/png, image/jpeg и т.д.
    size          bigint       not null,       -- размер в байтах
    item_type     varchar(30),                 -- QUESTION | LANGUAGE_ITEM | null
    item_id       bigint,                      -- id вопроса или слова
    created_at    timestamptz  default now()
);

-- Индекс для выборки медиа по элементу (все картинки к вопросу)
CREATE INDEX idx_media_files_item ON media_files (item_type, item_id);
