CREATE TABLE users (
   id         bigint generated by default as identity primary key,
   username   varchar(100) not null unique,
   email      varchar(255) not null unique,
   created_at timestamptz default now()
);

-- 1. Вставляем себя
INSERT INTO users (username, email) VALUES ('alex', 'concitusira@gmail.com');

-- 1. Добавляем новую колонку
ALTER TABLE topics ADD COLUMN type varchar(20) default 'GENERAL'; -- GENERAL | LANGUAGE

-- 2. Добавляем колонку без NOT NULL
ALTER TABLE srs_reviews ADD COLUMN user_id bigint references users(id);
-- 3. Проставляем всем существующим записям user_id = 1
UPDATE srs_reviews SET user_id = 1;
-- 4. Делаем NOT NULL
ALTER TABLE srs_reviews ALTER COLUMN user_id SET NOT NULL;
-- 5. Пересоздаём unique constraint с учётом user_id
ALTER TABLE srs_reviews DROP CONSTRAINT IF EXISTS uq_review;
ALTER TABLE srs_reviews ADD CONSTRAINT uq_review UNIQUE (user_id, item_type, item_id);

ALTER TABLE srs_reviews ADD COLUMN ease_factor numeric(4,2) DEFAULT 2.50;

-- история ревью (опционально, но полезно для FSRS и аналитики)
CREATE TABLE srs_review_history (
    id          bigint generated by default as identity primary key,
    review_id   bigint not null references srs_reviews (id),
    user_id     bigint not null references users (id),
    item_type   varchar(30) not null,
    item_id     bigint      not null,
    result      varchar(10) not null,  -- CORRECT | INCORRECT | HARD
    reviewed_at timestamptz default now()
);